baseURL = "https://idea90-blog.netlify.app/"
languageCode = "en-us"
title = "idea90 blog"
theme = "PaperMod"

disableKinds = ["taxonomy", "taxonomyTerm"]  # Optional: remove /tags and /categories pages

[pagination]
  pagerSize = 5

[params]
  author = "idea90"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
